### PR TITLE
Revert "Revert "fixed removeFallingObject function""

### LINKED ISSUE #12: State mutations work

### PR DESCRIPTION
**Pull request by tranhuuphucuong**
Reverts timotiousPrime/RocketLauncher#3

Don't mind the double "Revert" things....!

### CODE REVIEW

File: stateMutators.js [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    ...state,
+    basketPos: basketPos - value,
+});
+
+const moveBasketRightKey = (state, value) => ({
+    ...state,
+    basketPos: basketPos + value,
+});
+
+const moveBasketMouse = (state, value) => ({
```
Comment (poltak) [inline stateMutators.js]: This mutator is exactly the same as `setBasketValue` below. And the name indicates it's for the mouse movement, which is something for later I suppose. So this prob can be removed

File: stateMutators.js [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+    ...state,
+    basketPos: value,
+});
+
+const moveBasketLeftKey = (state, value) => ({
+    ...state,
+    basketPos: basketPos - value,
+});
+
+const moveBasketRightKey = (state, value) => ({
```
Comment (poltak) [inline stateMutators.js]: Just a naming issue: I don't see a reason for this mutator name to have "Key" at the end. It makes it tightly coupled to the idea of the pressing right key to move right, when the concept of which keys should be pressed is not really relevant here in the state management code. I'd just keep it as "moveBasketRight" and leave the decision of what key triggers this mutation up to the event handling logic. Same with the prev function

File: stateMutators.js [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    ...state,
+    score: value,
+});
+
+const resetScore = (state) => ({
+    ...state,
+    score: 0,
+});
+
+const setLivesRemaining = (state, value) => ({
```
Comment (poltak) [inline stateMutators.js]: In the context of our game I think lives only either:
- decrease, when you are penalized
- reset, when you start a game

So rather than a `setLivesRemaining` "setter" style mutator, maybe a `loseLife` mutator that always minuses 1 from `livesRemaining` state makes more sense. 

(not saying you're necessarily wrong here - this would still work fine, and could be more flexible if maybe we add more ways later to get/lose lives - but just an example of how state mutations can be thought of differently when relating back to the program's functionality)

File: stateMutators.js [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+    ...state,
+    gameLevel: 0,
+});
+
+const setGameMode = (state, value) => ({
+    ...state,
+    gameMode: value,
+});
+
+function addFallingObject (state, fallingObj) {
```
Comment (poltak) [inline stateMutators.js]: This and the mutators below are a little bit different to the others in that they don't return anything, while the previous all return the new state. i.e., their [function/type signature](https://developer.mozilla.org/en-US/docs/Glossary/Signature/Function) is different

These ones should be updated to have the same signature so they can be used in the same ways

File: stateMutators.js [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+    state.fallingObjects.push(fallingObj)
+};
+
+function removeFallingObject (state, fallingObj) {
+    let objectIndex = state.fallingObjects.indexOf(fallingObj)
```
Comment (poltak) [inline stateMutators.js]: This is going to cause issues if the `fallingObj` param passed in is not the exact same prototype instance as is stored in state. That could be likely, depending on how the logic is used. Instead it might be easier to keep track of the number of objects spawned and use that count as an ID field in `FallingObject`. Then each object has a unique ID which we can refer to it by, instead of relying on the exact object instance. I would just keep it like this for now, but be aware we might change it soon if it makes sense to

File: stateMutators.js [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+// Object constructor for falling object
+function FallingObject(posX, posY, numerator, denominator) {
+    this.posX = posX;
+    this.posY = posY;
+    this.numerator = numerator;
+    this.denominator = denominator;
+    this.value = numerator / denominator
+}
+
+const setFallingObjPosX = (fallingObj, value) => {
```
Comment (poltak) [inline stateMutators.js]: Apart from `posY` I don't think any of these states actually change after creation of the `FallingObject` instance, right? Therefore, I don't think these mutators don't need to exist apart from the one that mutates `posY`.

It would also be good to ensure the first param is `state`, to keep type signature consistency (and return the new state)

**Review by poltak — CHANGES_REQUESTED** [review]
@timotiousPrime I left some review points. No need to address/reply to everything. Some are just ideas. The key issues to address are some of the mutators not returning the new state, and some of them not having `state` as the first param.

Nice work btw! Love how the state is nice and small. This seems pretty doable :D

File: stateMutators.js (hunk 1 above)
Comment (timotiousPrime) [reply stateMutators.js]: How is it that same as setBasketValue? moveBasketMouse has the basketPos property and setBasketValue has the basketValue property? Am I maybe not understanding you properly?

File: stateMutators.js (hunk 2 above)
Comment (timotiousPrime) [reply stateMutators.js]: The use of 'Key' was to distinguish between the basket being moved by the mouse or when a key is pressed. I'll update it

File: stateMutators.js (hunk 4 above)
Comment (timotiousPrime) [reply stateMutators.js]: updated

File: stateMutators.js (hunk 6 above)
Comment (timotiousPrime) [reply stateMutators.js]: You're right, I was expecting this to set the position on the x axis, but I forgot it's set in the object constructor. Thanks Jon

File: stateMutators.js (hunk 1 above)
Comment (poltak) [reply stateMutators.js]: You're right. I thought they were both mutating `basketPos`, but they're different in that way. Too tired when I looked at this :S 

Though yeah I'd still rename this `setBasketPos` to remove the tight coupling to the idea of the context in which this mutator will be used (similar to the `moveBasketRightKey` one below)

Comment (timotiousPrime) [reply stateMutators.js]: So something like `moveBasket` and then remove `moveBasketLeft`, `moveBasketRight` and `moveBasketMouse`?

Comment (poltak) [reply stateMutators.js]: no, the `moveBasketLeft` and `moveBasketRight` names are fine. They correspond to core changes in the game's state/how the game works. 

`moveBasketMouse` does not. This name corresponds to a specific input method, which makes it hard to be used in other contexts because the name ties it to a single specific way of use. So i'd just rename this `setBasketPosition` then it can be used for the mouse movement and any other context in which we need to move the basket later.

Naming is a surprisingly difficult part of programming in my experience. It's easy to write some names that makes sense at one time due to all the other stuff you have going through your head, though then give it to other people, or to your future self/s, who aren't thinking the same and the meaning gets interpreted differently leading to miscommunications. Thinking about things in different layers of responsiblity can help with this (e.g., main UI -> user input handling -> data (state) changes)
Some more thoughts on naming: https://hilton.org.uk/blog/why-naming-things-is-hard

File: stateMutators.js [hunk 7]
```diff
@@ -0,0 +1,109 @@
...
+});
+
+const setGameMode = (state, value) => ({
+    ...state,
+    gameMode: value,
+});
+
+const addFallingObject = (state, fallingObj) => ({
+    ...state,
+    fallingObjects: state.fallingObjects.push(fallingObj)
```
Comment (poltak) [inline stateMutators.js]: `Array.push` here actually returns a `number` value denoting the number of elements in the array rather than the array itself. Which means this mutation is going to overwrite the `fallingObjects` state with a single number value when this gets called. Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push#return_value

I can think of two ways you could update it to do what you want here:

1. using array destructuring to effectively add the new obj to the add of the array:
```js
const addFallingObject = (state, fallingObj) => ({
    ...state,
    fallingObjects: [
		...state.fallingObjects,
		fallingObj,
    ],
})
```

2. using `Array.push` to add it in a separate line, then return the changed state in the next line
```js
const addFallingObject = (state, fallingObj) => {
	state.fallingObjects.push(fallingObj)
	return state
}
```

I personally would do 1 as it creates a brand new array and state object each call (if your mutations return brand new objects every time they're called, you can do some fancy stuff like travel back and forwards in time through your state mutations, which can be useful for debugging and other things - though a bit more advanced concepts), and I find the `...` destructuring notation more self-descriptive of the data changes (though possibly subjective).

File: stateMutators.js [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+});
+
+const removeFallingObject = (state, fallingObjId) => ({
+    ...state,
+    fallingObjects: state.fallingObjects.splice(fallingObjId, 1)
```
Comment (poltak) [inline stateMutators.js]: This `.splice` call has a similar pitfall as the `.push` call above, as it returns the slice of the array that you specify via the two indices you pass in rather than the new array with those values removed. 

e.g., `[1,2,3,4].splice(2,1)` actually returns `[3]`, but you probably want the new state to be `[1,2,4]`.

In a similar way to above, two corresponding ways you could do this:

1. using array destructing + `.slice` calls to create a new array without that element:
```js
const removeFallingObject = (state, fallingObjId) => ({
    ...state,
    fallingObjects: [
		...state.fallingObjects.slice(0, fallingObjId),
		...state.fallingObjects.slice(fallingObjId + 1),
  	],
})
```

2. using `splice` in two lines:
```js
const removeFallingObject = (state, fallingObjId) => {
	state.fallingObjects.splice(fallingObjId, 1)
	return state
}
```

Again, I personally would chose 1 for the reasons above (creates brand new object, more readable), and it's more common in modern JS in my experience

File: stateMutators.js (hunk 1 above)
Comment (timotiousPrime) [reply stateMutators.js]: Thanks Jon, that makes sense. So seeing as I already have a mutator called setBasketPos, I removed the moveBasketMouse function all together

File: stateMutators.js (hunk 8 above)
Comment (timotiousPrime) [reply stateMutators.js]: roger that

File: stateMutators.js [hunk 9]
```diff
@@ -0,0 +1,174 @@
...
+            fallingObj,
+        ]
+    }
+};
+
+const removeFallingObject = (state, fallingObjId) => {
+    return {
+        ...state,
+        fallingObjects: [
+            ...state.fallingObjects.slice[0, fallingObjId],
```
Comment (poltak) [inline stateMutators.js]: `slice` is a function on `Array.prototype` so you need to use round brackets to call it. Square are for array or object index access. i.e., `.slice(0, fallingObjId)`

File: stateMutators.js [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+const setFallingObjDenominator = (fallingObj, value) => {
+    fallingObj.denominator = value;
+}
+
+// Calculating Functions
+
+const calcBasketValue = (state, basketValue, fallingObjectValue) => {
+    return {
+        ...state,
+        basketValue: basketValue + fallingObjectValue,
```
Comment (poltak) [inline stateMutators.js]: I think this function shouldn't have that second param `basketValue` as that should be derived from the first param `state` via `state.basketValue`. And this line would need updating

File: stateMutators.js [hunk 11]
```diff
@@ -0,0 +1,174 @@
...
+    }
+};
+
+
+const calcScore = (state, basketValue, score) => (
```
Comment (poltak) [inline stateMutators.js]: Same as the above with the 2nd and 3rd params. They can be derived from the first `state`.

I also would prefer `score: state.score + 1,`, or adding a new param you can pass in `score: state.score + scoreIncrease,`, rather than using `++` here though. This particular usage should work fine, but using `++` when setting things can easily lead to bugs as it also modifies the underlying variable - which lead to unexpected values in my experience.
Same with the `--livesRemaining` below

File: stateMutators.js [hunk 12]
```diff
@@ -0,0 +1,174 @@
...
+function FallingObject(posX, posY, numerator, denominator) {
+    this.posX = posX;
+    this.posY = posY;
+    this.numerator = numerator;
+    this.denominator = denominator;
+    this.value = numerator / denominator;
+    this.id = id;
+}
+
+const setFallingObjPosY = (fallingObj, value) => {
```
Comment (poltak) [inline stateMutators.js:141]: These ones should all return `fallingObj`. So they follow that convention of old state in, new state out. Even though this is not the full state, it still operates on a section of state and can be used easily in the same way. substate mutators

**Comment by poltak** [comment]
Nice mutations @timotiousPrime 🧬 I think we're almost there then we can start hooking them up to things

File: stateMutators.js (hunk 12 above)
Comment (timotiousPrime) [reply stateMutators.js:141]: updated

File: stateMutators.js (hunk 10 above)
Comment (timotiousPrime) [reply stateMutators.js]: I made basket an object so that it also can have it's own x position, width and height properties which will be used for the collision detection later on. So for these mutators, I have removed basketValue and replaced them with basket. Should I remove the basket param?

Comment (timotiousPrime) [reply stateMutators.js]: I removed basket after reading your next comment

File: stateMutators.js (hunk 11 above)
Comment (timotiousPrime) [reply stateMutators.js]: roger that

File: stateMutators.js (hunk 10 above)
Comment (poltak) [reply stateMutators.js]: I saw that. TBH I didn't like it at first as it makes the state more complicated, but the width and height states opens up the possibility of having different difficulties later where you might have a smaller/bigger basket. Let's go with it. Though I don't think there's a need for the basket's y position state, or do you disagree?

> Should I remove the basket param?

yeah these values are still all accessible at `state.basket.value`, etc. So still good to remove those params, as it makes things more simple (what we should always aim for)

File: stateMutators.js (hunk 9 above)
Comment (poltak) [reply stateMutators.js]: @timotiousPrime This got marked as resolved but it's still a problem in the code. Let me know if it's not clear

File: stateMutators.js [hunk 13]
```diff
@@ -0,0 +1,212 @@
...
+        height: 10
+    },
+    score: 0,
+    livesRemaining: 3,
+    gameLevel: 1,
+    gameMode: 'running',
+    fallingObjects: [],
+}
+
+const setBasketPos = (state, basket, value) => {
```
Comment (poltak) [inline stateMutators.js]: The `basket` param should be removed from this and the next few mutators. You can access the current state via `state.basket`

File: stateMutators.js [hunk 14]
```diff
@@ -0,0 +1,212 @@
...
+};
+
+const resetScore = (state) => {
+    return {
+        ...state,
+        score: 0,
+    }
+};
+
+const loseLife = (state, value) => {
```
Comment (poltak) [inline stateMutators.js]: The name of this mutator indicates to me that if I call it a life should be deducted. Though it takes in a value and sets the livesRemaining states to that value. So instead I'd remove the `value` param and just set the state to `livesRemaining - 1`

Comment (poltak) [reply stateMutators.js]: maybe this functionality is already covered by the `calcLives` mutator though. So maybe either just delete this one or call it inside `calcLives`

File: stateMutators.js (hunk 10 above)
Comment (timotiousPrime) [reply stateMutators.js]: I included the basket's y position because it's going to need to be set at some time, even if it's just once initially and I thought it'd be best to have all of it's properties in one place.

File: stateMutators.js (hunk 13 above)
Comment (timotiousPrime) [reply stateMutators.js]: Thanks for pointing those out, I missed them. Updated now

File: stateMutators.js (hunk 14 above)
Comment (timotiousPrime) [reply stateMutators.js]: I removed it, thanks Jon

File: stateMutators.js (hunk 10 above)
Comment (poltak) [reply stateMutators.js]: The basket's Y pos does need to be set at some time but, as it will likely never need to change, I'd still argue that it doesn't really belong here IMO. The setting of the basket Y pos could just be done in the HTML+CSS as it's static. State should be as minimal as possible, and only contain dynamic data that could change throughout the lifecycle of the program.

Similar to the reason we don't include things like X and Y position of the score box in state, for example. It's not anticipated to ever change in the course of the game, so it's going to be left up to the main styles code to define that. 

But it's not super important to get this all perfect. Once this gets merged, likely later on we'll realize there was some state change we were not anticipating and need to add support for. That's normal. The main point is try to identify if any values in state are actually static and thus probably shouldn't be there. So don't worry about removing this

File: stateMutators.js (hunk 9 above)
Comment (timotiousPrime) [reply stateMutators.js]: Sorry, I completely missed that I used the wrong brackets. I have updated it now
